name: build-sunxi-cortexa53-24.10.x

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: "请选择开发板型号"
        required: true
        options:
          - xunlong_orangepi-zero3
          - xunlong_orangepi-zero2
        default: xunlong_orangepi-zero3
      luci_version:
        description: "选择luci版本"
        required: false
        default: "24.10.3"
        type: choice
        options:
          - 24.10.0
          - 24.10.1
          - 24.10.2
          - 24.10.3
          - 24.10.4
      size:
        description: '请输入要编译固件大小 单位(MB)'
        required: true
        default: '1024'


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: |
          chmod +x ${{ github.workspace }}/sunxi-cortexa53/build24.sh 
      
      - name: Build sunxi-cortexa53 ImmpotalWrt 24.10.2
        run: |
          profiles="${{ github.event.inputs.profile }}"
          size="${{ github.event.inputs.size }}"
          luci_version="${{ github.event.inputs.luci_version }}"
          
          IFS=',' read -r -a profile_array <<< "$profiles"
          
          for profile in "${profile_array[@]}"; do
            echo "Building for profile: $profile"
            
            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
              -v "${{ github.workspace }}/files/etc/uci-defaults:/home/build/immortalwrt/files/etc/uci-defaults" \
              -v "${{ github.workspace }}/arch/arch.conf:/home/build/immortalwrt/files/etc/opkg/arch.conf" \
              -v "${{ github.workspace }}/shell:/home/build/immortalwrt/shell" \
              -v "${{ github.workspace }}/sunxi-cortexa53/build24.sh:/home/build/immortalwrt/build.sh" \
              -e PROFILE=$profile \
              -e ROOTSIZE=$size \
              immortalwrt/imagebuilder:sunxi-cortexa53-openwrt-${luci_version} /bin/bash /home/build/immortalwrt/build.sh
          done

      - name: Upload ImmortWrt as release assets
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: Autobuild-sunxi-cortexa53
          name: ImmortalWrt-sunxi-cortexa53
          body_path: ${{ github.workspace }}/sunxi-cortexa53/info.md
          files: |
            ${{ github.workspace }}/bin/targets/sunxi/cortexa53/*squashfs-sdcard.img.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
